version: '3.8'

services:
  
  web:
    
    build: .
    
    command: python /code/manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/code

    ports:
      - 8000:8000

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    depends_on:
      - db

  db:
    image: postgres:15
    
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

