version: '3.8'

services:
  
  web:
    
    build: .
    
    command: python /code/manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/code

    ports:
      - 8000:8000

    environment:
      - SECRET_KEY=h0$$mzfm=818osja*7vz$$jn)2zh%2zm#23u-38o980jc3^gcok
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    depends_on:
      - db

  db:
    image: postgres:15
    
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

